apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      annotations:
        ad.datadoghq.com/{{ .Values.app.name }}.logs: '[{"source": "java", "service": "{{ .Values.app.name }}", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: {{ .Values.app.name }}
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: KAFKA_BROKER
            value: {{ .Values.kafka.name }}
        ports:
          - containerPort: {{ .Values.service.targetPort }}
